wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1651907308
    t:
      1:
      - 2
      - 3
      - 55
      3:
      - 3
      - 8
      4: 3.8.5
      5: 0.12.16
      8:
      - 1
      - 3
      - 5
      10:
      - 1
      - 9
batch_size:
  desc: null
  value: 128
hidden_size:
  desc: null
  value:
  - 128
  - 256
learning_rate:
  desc: null
  value: 0.005
loss:
  desc: null
  value: sparse_categorical_crossentropy
metrics:
  desc: null
  value: accuracy
num_classes:
  desc: null
  value: 10
optimizer:
  desc: null
  value: adam
total_epochs:
  desc: null
  value: 3
